### ISSUE TITLE
Dropdowns have poor CSS

### ISSUE THREAD

**Issue by tstrader** [readmeio/api-explorer#136]
The padding on dropdowns for enum field types causes the text to get clipped as shown in the image below from the provided sample https://pet-store-api-explorer.readme.io/v1.0/reference?newApiExplorer=true#addpet
![image](https://user-images.githubusercontent.com/1448520/44547911-66ed3f00-a6d1-11e8-9fd8-147ece07d680.png)

**Comment by gkoberger** [comment]
@achalvs, want to take a look at this?

**Comment by achalvs** [comment]
@gkoberger yes!

**Comment by achalvs** [comment]
tentative fix pushed to `feature/restyling`, see here: https://github.com/readmeio/api-explorer/commit/47409f8ff5b2c8da4ed232a98a57a1a5992d7842

i believe it's because of padding, but can't test because unsure of os/browser combination. try `git checkout feature/restyling && rm -rf node_modules && npm i && npx lerna bootstrap && npm start` and let me know if all is well!

**Comment by domharrington** [comment]
Yup this was fixed there.
