### ISSUE TITLE
Auth input box needs to be filled again for each API 

### ISSUE THREAD

**Issue by perryloh-nintex** [readmeio/api-explorer#173]
Hi @domharrington, I've just enabled the new api explorer on our project(http://nintex.readme.io/v1.0/reference). Just noticed that the "instance" of the Auth input box isn't shared with the other APIs. If I filled in token for API #1, I'd have to fill token again for API #2 and so on. 
In the old API Explorer, the instance of that Auth input box was shared between the API's so you'd only have to fill it once(assuming its the same security scheme defined in your swagger).

Is this intentional ?

Thanks,
Perry

**Comment by domharrington** [comment]
Hey Perry! Thanks for reporting this. This definitely isn't intentional and it *should* work as it used to work. One way of making sure the API Keys are prefilled is to log your users into your docs using JWT: https://readme.readme.io/docs/getting-started-with-custom-authentication#section-jwt-link

Hope this helps!

**Comment by domharrington** [comment]
The state of the api keys should now be shared across all auth inputs. Please reopen if this is not the case! Fixed in #187
