### ISSUE TITLE
requestBody with oneOf schemas still producing error

### ISSUE THREAD

**Issue by DSchultzContractor** [readmeio/api-explorer#495]
I believe I am seeing the error that was supposed to have been resolved in Issue [#104](https://github.com/readmeio/api-explorer/issues/104)
 
With a request body like this:

```
components:
   requestBodies:
     requestBody1:
       content:
         application/json:
           schema:
             type: object
             properties:
               config:
                 oneOf:
                   - $ref: '#/components/schemas/schema1'
                   - $ref: '#/components/schemas/schema2'
             additionalProperties: false
```

I get this error in the API explorer:

```
Unsupported field schema for field TEST_config: Unknown field type undefined.

{
  "format": ""
}
```

**Comment by erunion** [comment]
What version of the Explorer are you seeing this on? Do you mind sharing your full OAS so I can see how `#/components/requestBodies/requestBody1` is used?

I'm having trouble replicating this at least with parameters in an example I added in our `one-of.json` document (https://github.com/readmeio/api-explorer/commit/31c29028ce49c967ebe3a272fa12068aa6638689).

https://preview.readme.io/?selected=swagger-files%2Fone-of.json

**Comment by DSchultzContractor** [comment]
I am seeing this issue when viewing the API Reference page under my project on readme.io. I'm not sure what version of API Explorer it is. I created a minimal OAS to work with for troubleshooting the issue, pasting it below. I tested with this and it does produce the error. I will also attach a screenshot of the error.

![Capture](https://user-images.githubusercontent.com/57688798/75396368-93c77700-58b1-11ea-945e-7eaf984bc3ed.PNG)

Here's the OAS:

openapi: 3.0.1

info:
  version: '1.0'
  title: 'Test oneOf in Schemas'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'https://{api_host}/api'
    variables:
      api_host:
        default: API_HOST
paths:
  /TEST:
    post:
      operationId: TEST
      security:
        - session_cookie_auth:
            - system_admin
      requestBody:
        $ref: '#/components/requestBodies/body'
      responses:
        default:
          $ref: '#/components/responses/default_error'
components:
  requestBodies:
    body:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              config:
                oneOf:
                  - $ref: '#/components/schemas/schema1'
                  - $ref: '#/components/schemas/schema2'
            additionalProperties: false
  responses:
    default_error:
      description: 'default error'
      content:
        application/json:
          schema:
            type: string
  schemas:
    schema1:
      type: string
    schema2:
      type: string
  securitySchemes:
    session_cookie_auth:
      type: apiKey
      name: X-Session-ID
      in: cookie
security:
  - session_cookie_auth: []

**Comment by DSchultzContractor** [comment]
I"m not sure what version it is - I am seeing the error when viewing the API Reference under my readme.io project. I created a minimal OAS which produces the error for troubleshooting and am attaching it here, along with a screenshot of the error.
![Capture](https://user-images.githubusercontent.com/57688798/75396533-f882d180-58b1-11ea-91b8-77a87c27f404.PNG)
[test-OAS.zip](https://github.com/readmeio/api-explorer/files/4258638/test-OAS.zip)

**Comment by erunion** [comment]
Brilliant, thank you. I'm looking into it now!

**Comment by erunion** [comment]
This appears to be a bug with a form module that we're using not being able to support `oneOf` without having a `type` alongside it. Adding one stops the error from happening, but exposes another bug in the same form module where the module kind of bugs out and a strange representation of the `oneOf` declaration because it can't seem to handle `$ref` inside of a nested `$oneOf`.

You can see this in action on the module's playground [here](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCJ9LCJzY2hlbWEiOnsiZGVmaW5pdGlvbnMiOnsiY29tcG9uZW50cyI6eyJzY2hlbWFzIjp7InNjaGVtYTEiOnsidHlwZSI6InN0cmluZyJ9LCJzY2hlbWEyIjp7InR5cGUiOiJzdHJpbmcifX19fSwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiY29uZmlnIjp7InR5cGUiOiJvYmplY3QiLCJvbmVPZiI6W3siJHJlZiI6IiMvZGVmaW5pdGlvbnMvY29tcG9uZW50cy9zY2hlbWFzL3NjaGVtYTEifSx7IiRyZWYiOiIjL2RlZmluaXRpb25zL2NvbXBvbmVudHMvc2NoZW1hcy9zY2hlbWEyIn1dfX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6dHJ1ZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==).

That said, I'm working to resolve these and a host of other issues with our lack of support for `allOf` in a release that's slated to hit over the next week or two.

In the meantime, you should be able to resolve your issues by adding a `type` at the same level of the `oneOf`, and also swapping the usages of `$ref` in those `oneOf`'s with the contents of those references.

**Comment by DSchultzContractor** [comment]
Thank you for the information. This isn't a show-stopper for us at this point so I won't need to implement the workaround if a fix is coming soon. I will watch for that update.

**Comment by erunion** [comment]
Thanks for your patience. I'll update this ticket when we've got a fix in production.

**Comment by erunion** [comment]
Hey @DSchultzContractor, just wanted to followup with you on this and let you know that this fix was just pushed out to production. Let me know if you still have any issues with it!

**Comment by DSchultzContractor** [comment]
@erunion Just tested and this is functioning as expected now. Appreciate the follow-up!
